language: csharp
mono: none
dotnet: 2.2.105

matrix:
  include:
    - os: linux
      dist: xenial
      env: CONFIGURATION=Debug
    - os: linux
      dist: xenial
      env: CONFIGURATION=Release

script:
 - cd src
 - dotnet build
 - cd Pipedrive.net.Tests
 - dotnet test -c $CONFIGURATION